version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
  flask:
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - 'db'
    restart: always
  vue:
    build: ./frontend
    ports:
      - '80:80'
    depends_on:
      - 'flask'
    restart: always

volumes:
  db:
